steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker', '${_CONT_REGISTRY_NAME}']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo '${_GCP_SA_KEY_BASE64}' | base64 -d > inference/gcp-sa-key.json
    # Verificar que el JSON es válido
    cat inference/secrets/gcp-sa-key.json | jq .
    echo "✅ Archivo creado correctamente"

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t',
    '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_API_IMAGE_NAME}:latest',
    '--cache-from',
    '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_API_IMAGE_NAME}:latest',
    'inference/.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_API_IMAGE_NAME}:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_CLOUD_RUN_SERVICE_NAME}'
  - '--image'
  - '${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_API_IMAGE_NAME}:latest'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - '^#^FIRESTORE_DB_NAME=${_FIRESTORE_DB_NAME}#GOOGLE_APPLICATION_CREDENTIALS=gcp-sa-key.json'


images: ['${_CONT_REGISTRY_NAME}/${_PROJECT_ID}/${_CONT_REPOSITORY_NAME}/${_CONT_API_IMAGE_NAME}:latest']

options:
  logging: CLOUD_LOGGING_ONLY