from enum import Enum

class ContentFileExtensionEnum(str, Enum):
    PDF = '.pdf'

class ContentMimeTypeEnum(str, Enum):
    PDF = "application/pdf"

class DocumentTypeEnum(str, Enum):
    INVOICE = "FACTURA"
    SITED = "SITED PRINCIPAL"
    SECUNDARY_SITED = "SITED SECUNDARIO"
    CREDIT_NOTE = "NOTA CREDITO"
    PRE_SETTLEMENT = "REPORTE PRE-LIQUIDACION PRINCIPAL"
    SETTLEMENT_SUMMARY = "REPORTE LIQUIDACION RESUMEN"
    SETTLEMENT_TYPE_1 = "REPORTE LIQUIDACION DETALLE PRINCIPAL"
    SETTLEMENT_TYPE_2 = "REPORTE LIQUIDACION DETALLE PRINCIPAL - LOGO"
    GUARANTEE_LETTER = "CARTA GARANTIA"
    OTHERS = "OTROS"
    EPICRISIS = "EPICRISIS"
    PRESCRIPTION = "RECETA MEDICA"
    PHARMACY_ATTENTION = "ATENCION FARMACIA"
    OPERATORY_REPORT = "INFORME OPERATORIO"


AUNA_BLOB_DIRECTORY = "auna/docs/pages"

MAX_PARALLEL_WORKERS = 100

DEFAULT_ENTITIES_EXTRACTION_MESSAGE = "Extrae las entidades correspondientes"

DEFAULT_EXPIRATION_TIME = 60*60

#CORE_AGENT_API = "http://localhost:9090"
CORE_AGENT_API = "https://api-auna-workflow-dev-106504408617.us-east4.run.app"

AGENT_ENDPOINT = "api/documents/proccess"

VALID_DOCUMENTS = ["F", "SITED"]

DOCUMENT_WINDOW_SIZE = 4

MAX_RETRIES = 3

DEFUALT_ENTITIES = []