from enum import Enum

LABEL_AGENT_KEY = "LABEL"
INVOICE_AGENT_KEY = "FACTURA"
SITED_AGENT_KEY = "SITED"
RM_AGENT_KEY = "RM"
CR_AGENT_KEY = "CR"

class DocumentKeyEnum(str, Enum):
    INVOICE_IMPORT_KEY = "INVOICE_IMPORT"
    SITED_IMPORT_KEY = "SITED_IMPORT_KEY"
    CREDIT_NOTE_KEY = "CREDIT_NOTE_KEY"
    PRE_SETTLEMENT_KEY = "PRE_SETTLEMENT_KEY"
    SETTLEMENT_SUMMARY_KEY = "SETTLEMENT_SUMMARY_KEY"
    SETTLEMENT_TYPE_1_KEY = "SETTLEMENT_TYPE_1_KEY"
    SETTLEMENT_TYPE_2_KEY = "SETTLEMENT_TYPE_2_KEY"
    GUARANTEE_LETTER_KEY = "GUARANTEE_LETTER_KEY"
    EPICRISIS_KEY = "EPICRISIS_KEY"
    PRESCRIPTION_KEY = "PRESCRIPTION_KEY"
    PHARMACY_ATTENTION_KEY = "PHARMACY_ATTENTION_KEY"
    OPERATORY_REPORT_KEY = "OPERATORY_REPORT_KEY"

class BigQueryInsertionMode(str, Enum):
    APPEND = 'append'
    REPLACE = 'replace'

DEFAULT_EXPIRATION_TIME = 60

BASE_URL_EMAIL_SERVICE = "https://b6lrie69zf.execute-api.us-east-2.amazonaws.com/desa"
ENDPOINT_NOTIFICATION_SERVICE = "notificacioncorreo"

class TypeAttachedFile(str, Enum):
    URL = 'url'
    BUCKET = 'bucket'

class ScaleNumber(str, Enum):
    MILES = 'M'
    MILLIONS = 'MM'

MAPPER_SCALE = {
    'M': 1000,
    'MM': 1000000
}

DEFAULT_NUMERIC_SCALE = 9