name: 1. Deploy Artifacts 

on:
  workflow_dispatch:
    inputs:
      _ARTIFACT:
        description: 'Artifact'
        required: true
        default: "pipelines"
        type: choice
        options:
          - pipelines
          - web-ui
          - api
jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs._ARTIFACT }} environment
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.event.inputs._ARTIFACT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Verify deployment information
      run: |
        echo "Deploying to DEV ${{ github.event.inputs._ARTIFACT }}"
        echo "Project ID: ${{ vars.PROJECT_ID }}"
        echo "Registry: ${{ vars.CONT_REGISTRY_NAME }}"
        echo "Repository: ${{ vars.CONT_REPOSITORY_NAME }}"
        echo "Image name: ${{ vars.CONT_IMAGE_PROCESS_NAME }}"

      
    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'


    - name: Create GCP Service Account JSON file
      run: |
        mkdir -p pipelines/secrets
        mkdir -p web-ui/secrets
        mkdir -p api/secrets
        
        # Guardar el secreto como archivo JSON
        echo '${{ secrets.GCP_SA_KEY }}' > pipelines/secrets/gcp-sa-key.json
        echo '${{ secrets.GCP_SA_KEY }}' > web-ui/secrets/gcp-sa-key.json
        echo '${{ secrets.GCP_SA_KEY }}' > api/secrets/gcp-sa-key.json
        
        # Verificar que se creó correctamente
        echo "✅ GCP Service Account JSON created at pipelines/secrets/gcp-sa-key.json"
        ls -la web-ui/secrets/
        ls -la pipelines/secrets/
        ls -la api/secrets/

    - name: Deploy Pipelines
      if: github.event.inputs._ARTIFACT == 'pipelines'
      run: |
        SCHEDULE_PROCESS_INTERVAL="${{ vars.DAG_PROCESS_SCHEDULE_INTERVAL }}"
        SCHEDULE_SUMMARY_PROCESS_INTERVAL="${{ vars.DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL }}"
        
        gcloud builds submit --project=${{ vars.PROJECT_ID }} \
          --substitutions=_CONT_IMAGE_NAME=${{ vars.CONT_IMAGE_NAME }},_CONT_IMAGE_PROCESS_NAME=${{ vars.CONT_IMAGE_PROCESS_NAME }},_CONT_IMAGE_SUMMARY_PROCESS_NAME=${{ vars.CONT_IMAGE_SUMMARY_PROCESS_NAME }},_PROJECT_ID=${{ vars.PROJECT_ID }},_CONT_REPOSITORY_NAME=${{ vars.CONT_REPOSITORY_NAME }},_CONT_REGISTRY_NAME=${{ vars.CONT_REGISTRY_NAME }},_DAG_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_PROCESS_INTERVAL",_DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_SUMMARY_PROCESS_INTERVAL",_DAG_BUCKET_PATH=${{ vars.DAG_BUCKET_PATH }},_DAG_ENV=${{ vars.DAG_ENV }} \
          --config=cloudbuild/pipelines.yaml
      
    - name: Deploy Web UI
      if: github.event.inputs._ARTIFACT == 'web-ui'
      run: |
        SCHEDULE_PROCESS_INTERVAL="${{ vars.DAG_PROCESS_SCHEDULE_INTERVAL }}"
        SCHEDULE_SUMMARY_PROCESS_INTERVAL="${{ vars.DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL }}"
        
        gcloud builds submit --project=${{ vars.PROJECT_ID }} \
          --substitutions=_CONT_IMAGE_NAME=${{ vars.CONT_IMAGE_NAME }},_CONT_IMAGE_PROCESS_NAME=${{ vars.CONT_IMAGE_PROCESS_NAME }},_CONT_IMAGE_SUMMARY_PROCESS_NAME=${{ vars.CONT_IMAGE_SUMMARY_PROCESS_NAME }},_PROJECT_ID=${{ vars.PROJECT_ID }},_CONT_REPOSITORY_NAME=${{ vars.CONT_REPOSITORY_NAME }},_CONT_REGISTRY_NAME=${{ vars.CONT_REGISTRY_NAME }},_DAG_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_PROCESS_INTERVAL",_DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_SUMMARY_PROCESS_INTERVAL",_DAG_BUCKET_PATH=${{ vars.DAG_BUCKET_PATH }},_DAG_ENV=${{ vars.DAG_ENV }} \
          --config=cloudbuild/web-ui.yaml
      
    - name: Deploy API
      if: github.event.inputs._ARTIFACT == 'api'
      run: |
        SCHEDULE_PROCESS_INTERVAL="${{ vars.DAG_PROCESS_SCHEDULE_INTERVAL }}"
        SCHEDULE_SUMMARY_PROCESS_INTERVAL="${{ vars.DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL }}"
        
        gcloud builds submit --project=${{ vars.PROJECT_ID }} \
          --substitutions=_CONT_IMAGE_NAME=${{ vars.CONT_IMAGE_NAME }},_CONT_IMAGE_PROCESS_NAME=${{ vars.CONT_IMAGE_PROCESS_NAME }},_CONT_IMAGE_SUMMARY_PROCESS_NAME=${{ vars.CONT_IMAGE_SUMMARY_PROCESS_NAME }},_PROJECT_ID=${{ vars.PROJECT_ID }},_CONT_REPOSITORY_NAME=${{ vars.CONT_REPOSITORY_NAME }},_CONT_REGISTRY_NAME=${{ vars.CONT_REGISTRY_NAME }},_DAG_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_PROCESS_INTERVAL",_DAG_SUMMARY_PROCESS_SCHEDULE_INTERVAL="$SCHEDULE_SUMMARY_PROCESS_INTERVAL",_DAG_BUCKET_PATH=${{ vars.DAG_BUCKET_PATH }},_DAG_ENV=${{ vars.DAG_ENV }} \
          --config=cloudbuild/api.yaml
      